// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/example/interview-stack/go-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProductStoreMock is an autogenerated mock type for the ProductStore type
type ProductStoreMock struct {
	mock.Mock
}

type ProductStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductStoreMock) EXPECT() *ProductStoreMock_Expecter {
	return &ProductStoreMock_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *ProductStoreMock) CreateProduct(ctx context.Context, product domain.Product) (*domain.Product, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product) (*domain.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Product) *domain.Product); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStoreMock_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductStoreMock_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *ProductStoreMock_Expecter) CreateProduct(ctx interface{}, product interface{}) *ProductStoreMock_CreateProduct_Call {
	return &ProductStoreMock_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *ProductStoreMock_CreateProduct_Call) Run(run func(ctx context.Context, product domain.Product)) *ProductStoreMock_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Product))
	})
	return _c
}

func (_c *ProductStoreMock_CreateProduct_Call) Return(_a0 *domain.Product, _a1 error) *ProductStoreMock_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStoreMock_CreateProduct_Call) RunAndReturn(run func(context.Context, domain.Product) (*domain.Product, error)) *ProductStoreMock_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *ProductStoreMock) DeleteProduct(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStoreMock_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type ProductStoreMock_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProductStoreMock_Expecter) DeleteProduct(ctx interface{}, id interface{}) *ProductStoreMock_DeleteProduct_Call {
	return &ProductStoreMock_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *ProductStoreMock_DeleteProduct_Call) Run(run func(ctx context.Context, id string)) *ProductStoreMock_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProductStoreMock_DeleteProduct_Call) Return(_a0 bool, _a1 error) *ProductStoreMock_DeleteProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStoreMock_DeleteProduct_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *ProductStoreMock_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *ProductStoreMock) GetProduct(ctx context.Context, id string) (*domain.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStoreMock_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type ProductStoreMock_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProductStoreMock_Expecter) GetProduct(ctx interface{}, id interface{}) *ProductStoreMock_GetProduct_Call {
	return &ProductStoreMock_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *ProductStoreMock_GetProduct_Call) Run(run func(ctx context.Context, id string)) *ProductStoreMock_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProductStoreMock_GetProduct_Call) Return(_a0 *domain.Product, _a1 error) *ProductStoreMock_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStoreMock_GetProduct_Call) RunAndReturn(run func(context.Context, string) (*domain.Product, error)) *ProductStoreMock_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields: ctx
func (_m *ProductStoreMock) Health(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductStoreMock_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type ProductStoreMock_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProductStoreMock_Expecter) Health(ctx interface{}) *ProductStoreMock_Health_Call {
	return &ProductStoreMock_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *ProductStoreMock_Health_Call) Run(run func(ctx context.Context)) *ProductStoreMock_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProductStoreMock_Health_Call) Return(_a0 error) *ProductStoreMock_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductStoreMock_Health_Call) RunAndReturn(run func(context.Context) error) *ProductStoreMock_Health_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function with given fields: ctx
func (_m *ProductStoreMock) ListProducts(ctx context.Context) ([]domain.Product, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Product, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStoreMock_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type ProductStoreMock_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProductStoreMock_Expecter) ListProducts(ctx interface{}) *ProductStoreMock_ListProducts_Call {
	return &ProductStoreMock_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx)}
}

func (_c *ProductStoreMock_ListProducts_Call) Run(run func(ctx context.Context)) *ProductStoreMock_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProductStoreMock_ListProducts_Call) Return(_a0 []domain.Product, _a1 error) *ProductStoreMock_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStoreMock_ListProducts_Call) RunAndReturn(run func(context.Context) ([]domain.Product, error)) *ProductStoreMock_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, id, product
func (_m *ProductStoreMock) UpdateProduct(ctx context.Context, id string, product domain.Product) (*domain.Product, error) {
	ret := _m.Called(ctx, id, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Product) (*domain.Product, error)); ok {
		return rf(ctx, id, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Product) *domain.Product); ok {
		r0 = rf(ctx, id, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Product) error); ok {
		r1 = rf(ctx, id, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStoreMock_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type ProductStoreMock_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - product domain.Product
func (_e *ProductStoreMock_Expecter) UpdateProduct(ctx interface{}, id interface{}, product interface{}) *ProductStoreMock_UpdateProduct_Call {
	return &ProductStoreMock_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, id, product)}
}

func (_c *ProductStoreMock_UpdateProduct_Call) Run(run func(ctx context.Context, id string, product domain.Product)) *ProductStoreMock_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Product))
	})
	return _c
}

func (_c *ProductStoreMock_UpdateProduct_Call) Return(_a0 *domain.Product, _a1 error) *ProductStoreMock_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStoreMock_UpdateProduct_Call) RunAndReturn(run func(context.Context, string, domain.Product) (*domain.Product, error)) *ProductStoreMock_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductStoreMock creates a new instance of ProductStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductStoreMock {
	mock := &ProductStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
